### ISSUE TITLE
minor improvements in the last sync list

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#1022]
On pages like https://beta.bdrc.io/tradition/bo/ having the ability to just browse through the list of latest syncs is really helpful... but! I think we should have an option to ease it a little bit, for instance:
- selecting "Text" as the filter on type by default
- selecting "Tibetan" as the filter on language by default
- having the first sync date filter be on top
- have the collection filter also on top (below the first sync)
- have an option to display 50 results per page instead of the current small amount (or maybe 50 should just be the default?)

**Comment by berger-n** [comment]
done: [link](https://library-dev.bdrc.io/?sortBy=firstScanSyncDate_desc&type%5B0%5D=Instance)
- not added the Tibetan language filter for Recent Acquisitions on homepage (only on Tibetan tradition page)
- I assumed you meant 20 not 50 (20 is the number of results we display on search results page) 

<img width="720" src="https://github.com/user-attachments/assets/f830d3b8-a775-46a3-808f-9348f0c676a1" />

**Comment by eroux** [comment]
maybe it's just not deployed, but it seems the filter on "text" is not set by default on the recent acquisitions on https://library-dev.bdrc.io/ and https://beta.bdrc.io , can you set it @berger-n ?

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io / https://beta.bdrc.io

![Image](https://github.com/user-attachments/assets/c0c90baa-1399-4542-a91c-a7aca62db365)

**Comment by eroux** [comment]
thanks! https://beta.bdrc.io/ and library-dev still don't work in a Chrome incognito window though

**Comment by berger-n** [comment]
not working in what way? everything looks fine to me:

![Image](https://github.com/user-attachments/assets/218ef67d-5a67-4562-9b2c-bd730bebd552)

**Comment by eroux** [comment]
hah... nevermind it works now! My Internet connection is a bit bumpy, that might have been part of the issue... I don't know, in any case it works, thanks!

**Comment by berger-n** [comment]
> can we add the possiblity to search a keyword in the "latest syncs"? With the same design as when we search the publication by an author (the white search bar)?

done: 
- https://library-dev.bdrc.io/
  
  ![Image](https://github.com/user-attachments/assets/4bc441bb-cf16-48ad-bcb8-4b465a24cb6c)

---

- https://library-dev.bdrc.io/tradition/bo/
  
  ![Image](https://github.com/user-attachments/assets/7df59f37-4fdb-4483-a895-51ca70bd2370)
