### ISSUE TITLE
Number of teachers and students (associated persons) is 1 less than the amount that appears on tbrc.org

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/public-digital-library#227]
I've noticed that the equivalent of "associated persons" on BUDA consistently omits one person from the list of associated persons that appear on TBRC.org, at least when it comes to teachers and students. Below are screen grabs from P802 that show this.
On TBRC.org the lama has 4 teachers and 10 students and on BUDA he has 3 teachers and 9 students.  
<img width="693" alt="Screen Shot 2020-08-15 at 11 29 08 AM" src="https://user-images.githubusercontent.com/44705185/90315726-b09d4880-deeb-11ea-8a28-d6303c096da0.png">
<img width="350" alt="Screen Shot 2020-08-15 at 11 28 52 AM" src="https://user-images.githubusercontent.com/44705185/90315727-b135df00-deeb-11ea-8feb-c15c1bc42808.png">

**Comment by eroux** [comment]
wow, this is very bizarre... @berger-n this is a bug in the UI, the query returns all the 4 teachers

**Comment by berger-n** [comment]
I cannot reproduce this bug, even with Safari... @eroux can you?

![image](https://user-images.githubusercontent.com/33383857/90378383-942f1680-e079-11ea-9d3a-46d04a49833c.png)

@JannTibetan could you please provide the system & browser version numbers?

**Comment by eroux** [comment]
indeed, I can't reproduce either

**Comment by JannTibetan** [comment]
<img width="1271" alt="Screen Shot 2020-08-17 at 8 34 45 AM" src="https://user-images.githubusercontent.com/44705185/90396630-8d49d900-e064-11ea-98e8-bba361d8f561.png">

The weirdness is still occurring for me 
<img width="396" alt="Screen Shot 2020-08-17 at 8 35 45 AM" src="https://user-images.githubusercontent.com/44705185/90396694-a783b700-e064-11ea-928d-ba6da48c568f.png">
<img width="698" alt="Screen Shot 2020-08-17 at 8 35 59 AM" src="https://user-images.githubusercontent.com/44705185/90396709-b0748880-e064-11ea-863a-e941582fc92f.png">

**Comment by JannTibetan** [comment]
Update: the problem does not occur with Firefox or Chrome.

**Comment by JannTibetan** [comment]
Update 2: I just clear the cache, restarted Safari, and still had the same problem.

**Comment by JannTibetan** [comment]
I'm going to close this as it is a browser issue and not a BUDA bug

**Comment by eroux** [comment]
oh, this happens all the time, we have a lot of users on Safari so we'll fix it

**Comment by berger-n** [comment]
some follow-up here as I found another [great crossbrowser testing site with extensive free trial](https://saucelabs.com/) that allowed me to load the page on a real Safari 13 under MacOS Catalina/10.15

the issue is related to screen resolution:
- smaller than 1920px:
![image](https://user-images.githubusercontent.com/33383857/90493092-37e3f980-e142-11ea-9e34-a2960588ba70.png)
- 1920px and larger:
![image](https://user-images.githubusercontent.com/33383857/90494508-dd4b9d00-e143-11ea-87b2-18c6b9b85c05.png)

**Comment by eroux** [comment]
Ah great find! The website is $30 a month when billed monthly... this issues are bound to happen a lot in the next 3 or 4 month... @JannTibetan perhaps we could get an account and stop it in a few months?

**Comment by berger-n** [comment]
seems to be fixed now:

![image](https://user-images.githubusercontent.com/33383857/90510321-0fb4c480-e15b-11ea-8014-202a321be15b.png)

**Comment by JannTibetan** [comment]
Yes, let's pay for this service.

**Comment by JannTibetan** [comment]
And yes, it's fixed now. Good catch!

**Comment by eroux** [comment]
@JannTibetan did you reopen the issue because you're still experiencing it?

**Comment by eroux** [comment]
closing, @JannTibetan don't hesitate to reopen if you still experience this
