### ISSUE TITLE
improve multi-labels in canvas in reading view

### ISSUE THREAD

**Issue by eroux** [buda-base/public-digital-library#294]
in the reading view of https://library.bdrc.io/view/bdr:I4CZ75258 there's more than one label per language per image, the way Mirador currently handles it is to display for instance `1b<br />img.4`, instead it should display something like `1b  —  img.4`

**Comment by berger-n** [comment]
now uses saved locale from `/show` route
and added "uilang" url parameter than can override it 
https://library.bdrc.io/view/bdr:I4CZ75258?uilang=zh&lang=bo-x-ewts

**Comment by berger-n** [comment]
![image](https://user-images.githubusercontent.com/33383857/95876560-7af1d000-0d73-11eb-801a-f48dc2194259.png)

also works in tibetan: https://library.bdrc.io/view/bdr:I4CZ75258?uilang=bo

![image](https://user-images.githubusercontent.com/33383857/95876711-9fe64300-0d73-11eb-8094-29064842207c.png)

regarding translation for now we at least need "Show Images" and "Download Etext"
and maybe the dash between pages  " - "

**Comment by eroux** [comment]
ah excellent, thanks!

Can we have `  —  ` (space, space, emdash, space space) instead of ` - ` (space, dash, space)? Also, the Tibetan font should be bigger

**Comment by berger-n** [comment]
done:

![image](https://user-images.githubusercontent.com/33383857/95885249-54d12d80-0d7d-11eb-8813-a6c80e174ddb.png)


![image](https://user-images.githubusercontent.com/33383857/95885119-2eab8d80-0d7d-11eb-8b43-7c6436dd8fa9.png)

**Comment by eroux** [comment]
great, thanks!

**Comment by eroux** [comment]
I just noticed that the `<br/>` still appeared in the thumbnails of the image view:

![Capture d’écran de 2020-10-15 13-55-43](https://user-images.githubusercontent.com/60868/96120198-700f7a80-0eee-11eb-9f14-a774ec2efe22.png)

can we update it there too?

**Comment by berger-n** [comment]
fixed it:

![image](https://user-images.githubusercontent.com/33383857/96140265-08622b00-0f00-11eb-9a6d-ed6b0d76f7ce.png)

**Comment by eroux** [comment]
excellent, thanks!
