### ISSUE TITLE
Filter order (for test)

### ISSUE THREAD

**Issue by berger-n** [buda-base/public-digital-library#929]
Search in Etexts Only
Author
Print method
Scans access
Etext access
Etext quality
Associated tradition
Genre
Is about
Script
Language
Century
Place type
Gender
In Collection
Type
First scan sync date (change the label to "First scan date")
Sort by (change "sync scan date" to "Newest scans")

**Comment by berger-n** [comment]
done: https://library-dev.bdrc.io/osearch/search?

![image](https://github.com/user-attachments/assets/3dc39677-fa06-49a4-a88b-dd2e0c3a7e72)

**Comment by roopeux** [comment]
The screenshot is good.  The link still shows the wrong order.

**Comment by roopeux** [comment]
Thanks!
